
trigger:
 branches:
   include:
     - main 

pool:
  vmImage: ubuntu-latest

# variables:
  # imageRepositiry:"kuberockapp/nginx:latest"
  # clusterName:
  # namespace:
  # dockerfilePath:
  # serviceConnection:

stages:
- stage:"BUild"
  displayName:"Build"
  jobs:
  - job:"Build"
    displayName: "Build Stage"
    steps:
    - script: echo Hello, world to the Azure DevOps Pipelines!
      displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
