trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Checkout
  jobs:
  - job: Checkout
    steps: 
    - bash: echo "This is Checkout stage"
- stage: Build
  jobs:
  - job: Build
    steps: 
    - bash: echo "This is Build Stage"
- stage: SonarQubeAnaysis
  jobs:
  - job: SonarQubeAnaysis
    steps: 
    - bash: echo "This is SonarQube Anaysis Stage"
- stage: BuildPushDockerImages
  jobs:
  - job: BuildPushDockerImages
    steps: 
    - bash: echo "This is Build & Push Docker Images Stage"
- stage: DeploytoKubernetesCluster
  jobs:
  - job: DeploytoKubernetesCluster
    steps: 
    - bash: echo "This is Deploy to Kubernetes Cluster Stage"
