trigger:
- main

pool:
  vmImage: ubuntu-latest

stages: 
- stage: Checkout
  jobs:
  - job: Checkout
    steps: 
    - bash: echo "This is Checkout stage"
- stage: Build
  jobs:
  - job: Build
    steps: 
    - bash: echo "This is Build Stage"
- stage: SonarQube Anaysis
  jobs:
  - job: SonarQube Anaysis
    steps: 
    - bash: echo "This is SonarQube Anaysis Stage"
- stage: Build & Push Docker Images
  jobs:
  - job: Build & Push Docker Images
    steps: 
    - bash: echo "This is Build & Push Docker Images Stage"
- stage: Deploy to Kubernetes Cluster
  jobs:
  - job: Deploy to Kubernetes Cluster
    steps: 
    - bash: echo "This is Deploy to Kubernetes Cluster Stage"
