trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  platform: Dev

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps: 
    - bash: echo COmplete the compilation process
- stage: DevelopmentDeploy
  jobs:
  - deployment: DevelopmentDeploy
    environment: $(platform)
    strategy:
     runOnce:
       deploy:
         steps:
         - bash: echo Development Deployment 
- stage: QADeploy
  jobs:
  - deployment: QADeploy
    environment: $(platform)
    strategy:
     runOnce:
       deploy:
         steps:
         - bash: echo QADeploy Deployment