trigger:
- main

pool:
  vmImage: ubuntu-latest

# variables:
  # imageRepository: kuberakeshalagunde/vprofileweb:latest
  # clusterName: 
  # namespace:
  # dockerfilePath: Azure-DevOps-Kubernetes-Terraform/Dockerfile
  # serviceConnection:

stages:
- stage:
  jobs:
  - job: EnvironmentVariablesDetails
    steps:
    - bash: echo "First Job to show all the artifacts"
    - bash: echo $(Build.Buildnumber)
    - bash: echo $(Build.BuildID)
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $(Build.SourcesDirectory)
    - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    # - bash: java -version
    # - bash: node --version
    # - bash: python --version 
    # - bash: mvn -version 
    # - bash: echo "Before copying the files" ls -R $(Build.ArtifactStagingDirectory)
    # - task: CopyFiles@2
    #   inputs:
    #     SourceFolder: '$(System.DefaultWorkingDirectory)'
    #     Contents: |
    #       **/*.yml
    #       **/*.tf
    #     TargetFolder: '$(Build.ArtifactStagingDirectory)'
    # - bash: echo "After copying the files" ls -R $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'PRODArtifact'
        publishLocation: 'Container'
